version: '3.8'

services:
  # The PostgreSQL Database Service
  database:
    image: postgres:15-alpine
    container_name: mentorship-db
    restart: always
    env_file:
      - ./.env # Load variables from the root .env file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # Map container port 5432 to host port 5433 to avoid conflicts
    volumes:
      - db-data:/var/lib/postgresql/data # Persist database data

  # The Node.js Backend Service
  server:
    build:
      context: ./server # Look for the Dockerfile in the 'server' directory
    container_name: mentorship-server
    restart: always
    env_file:
      - ./.env # Load variables like DATABASE_URL and JWT_SECRET
    ports:
      - "5000:5000"
    depends_on:
      - database # Don't start the server until the database is ready

  # The React Frontend Service
  client:
    build:
      context: ./client # Look for the Dockerfile in the 'client' directory
    container_name: mentorship-client
    restart: always
    ports:
      - "3000:80" # Map container port 80 (Nginx) to host port 3000

# Define the named volume for data persistence
volumes:
  db-data: